name: SAST + Secret Scanning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  actions: read
  security-events: write

jobs:
  semgrep:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Semgrep
        run: |
          python3 -m pip install --upgrade pip
          pip3 install semgrep

      - name: Run Semgrep security scan
        run: semgrep --config https://semgrep.dev/p/php --error

      - name: Generate SARIF report
        run: semgrep --config https://semgrep.dev/p/php --sarif > semgrep.sarif

      - name: Upload SARIF results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

   secret-scan:
    name: Trufflehog Secret Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Trufflehog
        run: pip3 install truffleHog
      - name: Run Secret Scan
        run: trufflehog filesystem --entropy=True --max_depth 50 .
