name: SAST + Secret Scanning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  actions: read
  security-events: write

jobs:
  semgrep:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Semgrep
        run: |
          python3 -m pip install --upgrade pip
          pip3 install semgrep

      - name: Run Semgrep
        run: semgrep --config p/php --error --metrics || true

      - name: Generate SARIF
        run: semgrep --config p/php --sarif > semgrep.sarif || true

      - name: Upload SARIF results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif

  secret-scan:
    name: Secret scanning (Trufflehog)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Trufflehog
        run: pip3 install truffleHog

      - name: Run Trufflehog
        run: trufflehog filesystem --entropy=True --max_depth 50 . || true
